name: deploy to AWS EC2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create SSH key file
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > my-key.pem
        chmod 600 my-key.pem
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i my-key.pem ubuntu@${{ secrets.EC2_IP }} "cd /home/ubuntu/www/E_commerce && git pull origin master"

    - name: Clean up
      run: |
        rm my-key.pem
